# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BINARY_BUNDLE "OFF")
set(CPACK_BINARY_DEB "OFF")
set(CPACK_BINARY_DRAGNDROP "OFF")
set(CPACK_BINARY_FREEBSD "OFF")
set(CPACK_BINARY_IFW "OFF")
set(CPACK_BINARY_NSIS "OFF")
set(CPACK_BINARY_PRODUCTBUILD "OFF")
set(CPACK_BINARY_RPM "OFF")
set(CPACK_BINARY_STGZ "ON")
set(CPACK_BINARY_TBZ2 "OFF")
set(CPACK_BINARY_TGZ "ON")
set(CPACK_BINARY_TXZ "OFF")
set(CPACK_BUILD_SOURCE_DIRS "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1;/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_FILE_NAME "DEB-DEFAULT")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "GmSSL Vendor")
set(CPACK_DEBIAN_PACKAGE_RELEASE "1")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/opt/homebrew/Cellar/cmake/3.27.9/share/cmake/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "GmSSL built using CMake")
set(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE "ON")
set(CPACK_GENERATOR "STGZ;TGZ")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALL_CMAKE_PROJECTS "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl;GmSSL;ALL;/")
set(CPACK_INSTALL_PREFIX "/Users/cyx/easy_gmssl/GmSSL-Python/Core/gmssl_libs")
set(CPACK_MODULE_PATH ";/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/cmake")
set(CPACK_NOARCH_PACKAGE_RELEASE "1")
set(CPACK_NSIS_DISPLAY_NAME "GmSSL 3.1.1")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_MODIFY_PATH "ON")
set(CPACK_NSIS_PACKAGE_NAME "GmSSL 3.1.1")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "/opt/homebrew/opt/llvm/bin/llvm-objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/opt/homebrew/opt/llvm/bin/llvm-objdump")
set(CPACK_OSX_SYSROOT "/Library/Developer/CommandLineTools/SDKs/MacOSX14.2.sdk")
set(CPACK_OUTPUT_CONFIG_FILE "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "https://github.com/guanzhi/GmSSL/issues")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/README.md")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "GmSSL is an open source cryptographic toolbox that supports SM2 / SM3 / SM4 / SM9 and other national secret (national commercial password) algorithm. ")
set(CPACK_PACKAGE_FILE_NAME "GmSSL-3.1.1-Darwin")
set(CPACK_PACKAGE_HOMEPAGE_URL "http://gmssl.org")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "GmSSL 3.1.1")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "GmSSL 3.1.1")
set(CPACK_PACKAGE_NAME "GmSSL")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "GmSSL Vendor")
set(CPACK_PACKAGE_VERSION "3.1.1")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "1")
set(CPACK_PACKAGE_VERSION_PATCH "1")
set(CPACK_READELF_EXECUTABLE "/opt/homebrew/opt/llvm/bin/llvm-readelf")
set(CPACK_RESOURCE_FILE_LICENSE "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/LICENSE")
set(CPACK_RESOURCE_FILE_README "/opt/homebrew/Cellar/cmake/3.27.9/share/cmake/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/opt/homebrew/Cellar/cmake/3.27.9/share/cmake/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_FILE_NAME "RPM-DEFAULT")
set(CPACK_RPM_PACKAGE_GROUP "GmSSL Group")
set(CPACK_RPM_PACKAGE_RELEASE "1")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/CPackSourceConfig.cmake")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_SYSTEM_NAME "Darwin")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Darwin")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
