# CMake generated Testfile for 
# Source directory: /Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1
# Build directory: /Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(sm4 "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/bin/sm4test")
set_tests_properties(sm4 PROPERTIES  _BACKTRACE_TRIPLES "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;360;add_test;/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;0;")
add_test(sm3 "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/bin/sm3test")
set_tests_properties(sm3 PROPERTIES  _BACKTRACE_TRIPLES "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;360;add_test;/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;0;")
add_test(sm2 "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/bin/sm2test")
set_tests_properties(sm2 PROPERTIES  _BACKTRACE_TRIPLES "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;360;add_test;/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;0;")
add_test(sm9 "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/bin/sm9test")
set_tests_properties(sm9 PROPERTIES  _BACKTRACE_TRIPLES "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;360;add_test;/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;0;")
add_test(zuc "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/bin/zuctest")
set_tests_properties(zuc PROPERTIES  _BACKTRACE_TRIPLES "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;360;add_test;/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;0;")
add_test(aes "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/bin/aestest")
set_tests_properties(aes PROPERTIES  _BACKTRACE_TRIPLES "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;360;add_test;/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;0;")
add_test(sha224 "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/bin/sha224test")
set_tests_properties(sha224 PROPERTIES  _BACKTRACE_TRIPLES "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;360;add_test;/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;0;")
add_test(sha256 "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/bin/sha256test")
set_tests_properties(sha256 PROPERTIES  _BACKTRACE_TRIPLES "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;360;add_test;/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;0;")
add_test(sha384 "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/bin/sha384test")
set_tests_properties(sha384 PROPERTIES  _BACKTRACE_TRIPLES "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;360;add_test;/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;0;")
add_test(sha512 "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/bin/sha512test")
set_tests_properties(sha512 PROPERTIES  _BACKTRACE_TRIPLES "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;360;add_test;/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;0;")
add_test(chacha20 "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/bin/chacha20test")
set_tests_properties(chacha20 PROPERTIES  _BACKTRACE_TRIPLES "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;360;add_test;/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;0;")
add_test(hash_drbg "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/bin/hash_drbgtest")
set_tests_properties(hash_drbg PROPERTIES  _BACKTRACE_TRIPLES "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;360;add_test;/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;0;")
add_test(block_cipher "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/bin/block_ciphertest")
set_tests_properties(block_cipher PROPERTIES  _BACKTRACE_TRIPLES "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;360;add_test;/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;0;")
add_test(digest "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/bin/digesttest")
set_tests_properties(digest PROPERTIES  _BACKTRACE_TRIPLES "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;360;add_test;/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;0;")
add_test(hmac "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/bin/hmactest")
set_tests_properties(hmac PROPERTIES  _BACKTRACE_TRIPLES "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;360;add_test;/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;0;")
add_test(hkdf "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/bin/hkdftest")
set_tests_properties(hkdf PROPERTIES  _BACKTRACE_TRIPLES "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;360;add_test;/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;0;")
add_test(pbkdf2 "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/bin/pbkdf2test")
set_tests_properties(pbkdf2 PROPERTIES  _BACKTRACE_TRIPLES "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;360;add_test;/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;0;")
add_test(gf128 "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/bin/gf128test")
set_tests_properties(gf128 PROPERTIES  _BACKTRACE_TRIPLES "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;360;add_test;/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;0;")
add_test(gcm "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/bin/gcmtest")
set_tests_properties(gcm PROPERTIES  _BACKTRACE_TRIPLES "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;360;add_test;/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;0;")
add_test(aead "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/bin/aeadtest")
set_tests_properties(aead PROPERTIES  _BACKTRACE_TRIPLES "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;360;add_test;/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;0;")
add_test(pkcs8 "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/bin/pkcs8test")
set_tests_properties(pkcs8 PROPERTIES  _BACKTRACE_TRIPLES "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;360;add_test;/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;0;")
add_test(ec "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/bin/ectest")
set_tests_properties(ec PROPERTIES  _BACKTRACE_TRIPLES "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;360;add_test;/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;0;")
add_test(asn1 "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/bin/asn1test")
set_tests_properties(asn1 PROPERTIES  _BACKTRACE_TRIPLES "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;360;add_test;/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;0;")
add_test(hex "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/bin/hextest")
set_tests_properties(hex PROPERTIES  _BACKTRACE_TRIPLES "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;360;add_test;/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;0;")
add_test(base64 "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/bin/base64test")
set_tests_properties(base64 PROPERTIES  _BACKTRACE_TRIPLES "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;360;add_test;/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;0;")
add_test(pem "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/bin/pemtest")
set_tests_properties(pem PROPERTIES  _BACKTRACE_TRIPLES "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;360;add_test;/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;0;")
add_test(x509 "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/bin/x509test")
set_tests_properties(x509 PROPERTIES  _BACKTRACE_TRIPLES "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;360;add_test;/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;0;")
add_test(x509_oid "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/bin/x509_oidtest")
set_tests_properties(x509_oid PROPERTIES  _BACKTRACE_TRIPLES "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;360;add_test;/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;0;")
add_test(x509_alg "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/bin/x509_algtest")
set_tests_properties(x509_alg PROPERTIES  _BACKTRACE_TRIPLES "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;360;add_test;/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;0;")
add_test(x509_str "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/bin/x509_strtest")
set_tests_properties(x509_str PROPERTIES  _BACKTRACE_TRIPLES "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;360;add_test;/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;0;")
add_test(x509_ext "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/bin/x509_exttest")
set_tests_properties(x509_ext PROPERTIES  _BACKTRACE_TRIPLES "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;360;add_test;/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;0;")
add_test(x509_req "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/bin/x509_reqtest")
set_tests_properties(x509_req PROPERTIES  _BACKTRACE_TRIPLES "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;360;add_test;/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;0;")
add_test(x509_crl "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/bin/x509_crltest")
set_tests_properties(x509_crl PROPERTIES  _BACKTRACE_TRIPLES "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;360;add_test;/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;0;")
add_test(cms "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/bin/cmstest")
set_tests_properties(cms PROPERTIES  _BACKTRACE_TRIPLES "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;360;add_test;/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;0;")
add_test(tls "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/bin/tlstest")
set_tests_properties(tls PROPERTIES  _BACKTRACE_TRIPLES "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;360;add_test;/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;0;")
add_test(tls13 "/Users/cyx/easy_gmssl/GmSSL-Python/Core/build_gmssl/bin/tls13test")
set_tests_properties(tls13 PROPERTIES  _BACKTRACE_TRIPLES "/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;360;add_test;/Users/cyx/easy_gmssl/GmSSL-Python/Core/GmSSL-3.1.1/CMakeLists.txt;0;")
